import { StyleSheet } from 'react-native';

export const theme = {
  colors: {
    brand: {
      primary: '#1A56DB',
      primaryDark: '#0C3A7A',
      primaryLight: '#E8F0FE',
      admin: '#185FA5',
      primaryBorder: '#BFDBFE',
      verification: '#0D9E75',
      verificationDark: '#0A7A59',
      verificationLight: '#E0F5EE',
      ai: '#4F46E5',
      aiDark: '#312E81',
      aiLight: '#EEF2FF',
      aiBorder: '#C7D2FE',
      splash: '#174780',
      splashText: '#A8C6E8',
      splashTrack: 'rgba(255, 255, 255, 0.24)',
    },
    semantic: {
      success: '#1D9E75',
      successText: '#14532D',
      successBackground: '#D1FAE5',
      warning: '#D97706',
      warningText: '#B45309',
      warningBackground: '#FEF3C7',
      warningSubtle: '#FFFBEB',
      danger: '#EF4444',
      dangerDark: '#B91C1C',
      dangerText: '#991B1B',
      dangerBackground: '#FEE2E2',
      dangerSubtle: '#FEF2F2',
      dangerBorder: '#FECACA',
      info: '#1E40AF',
      infoBackground: '#EFF6FF',
    },
    background: {
      page: '#F9FAFB',
      adminPage: '#F5F5F3',
      surface: '#FFFFFF',
      disabled: '#F3F4F6',
    },
    text: {
      primary: '#111827',
      secondary: '#4B5563',
      tertiary: '#374151',
      muted: '#9CA3AF',
      disabled: '#D1D5DB',
      inverse: '#FFFFFF',
      link: '#1A56DB',
    },
    border: {
      default: '#E5E7EB',
      strong: '#D1D5DB',
      subtle: 'rgba(0, 0, 0, 0.06)',
      card: 'rgba(0, 0, 0, 0.08)',
    },
    onboarding: {
      mapBackground: '#E8F0FE',
      aiBackground: '#EEF2FF',
      verifyBackground: '#E0F5EE',
    },
  },
  spacing: {
    xxs: 2,
    xs: 4,
    s: 6,
    sm: 8,
    md: 10,
    lg: 12,
    xl: 14,
    page: 16,
    section: 18,
    screen: 20,
    xxl: 22,
    xxxl: 24,
    huge: 32,
  },
  radii: {
    xs: 6,
    sm: 8,
    md: 10,
    card: 12,
    lg: 14,
    hero: 18,
    circle: 999,
  },
  typography: {
    brandTitle: {
      fontSize: 30,
      lineHeight: 36,
      fontWeight: '500',
    },
    heroTitle: {
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '500',
    },
    screenTitle: {
      fontSize: 22,
      lineHeight: 29,
      fontWeight: '500',
    },
    sectionTitle: {
      fontSize: 15,
      lineHeight: 22,
      fontWeight: '500',
    },
    cardTitle: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
    },
    body: {
      fontSize: 13,
      lineHeight: 20,
      fontWeight: '400',
    },
    bodySmall: {
      fontSize: 12,
      lineHeight: 18,
      fontWeight: '400',
    },
    caption: {
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '400',
    },
    micro: {
      fontSize: 10,
      lineHeight: 13,
      fontWeight: '500',
    },
    overline: {
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '500',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
    },
    button: {
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '500',
    },
    buttonSmall: {
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '500',
    },
    sessionCode: {
      fontSize: 32,
      lineHeight: 32,
      fontWeight: '500',
      letterSpacing: 5,
    },
  },
  borders: {
    hairlineWidth: StyleSheet.hairlineWidth,
    cardWidth: StyleSheet.hairlineWidth,
    inputWidth: StyleSheet.hairlineWidth,
    dashedWidth: 1,
  },
  sizes: {
    touchTarget: 44,
    inputHeight: 48,
    inputHeightLarge: 52,
    primaryButtonHeight: 52,
    compactButtonHeight: 40,
    bottomNavHeight: 64,
    avatarSmall: 40,
    avatarCard: 60,
    otpBoxWidth: 44,
    otpBoxHeight: 52,
  },
  components: {
    card: {
      backgroundColor: '#FFFFFF',
      borderColor: '#E5E7EB',
      borderRadius: 12,
      borderWidth: StyleSheet.hairlineWidth,
      padding: 16,
    },
    input: {
      backgroundColor: '#FFFFFF',
      borderColor: '#E5E7EB',
      borderRadius: 10,
      borderWidth: StyleSheet.hairlineWidth,
      minHeight: 48,
      paddingHorizontal: 12,
    },
    primaryButton: {
      backgroundColor: '#1A56DB',
      borderRadius: 12,
      minHeight: 52,
    },
    secondaryButton: {
      backgroundColor: '#E8F0FE',
      borderRadius: 10,
      minHeight: 44,
    },
    segmentedRail: {
      backgroundColor: '#F3F4F6',
      borderRadius: 999,
      padding: 4,
    },
  },
  badges: {
    active: {
      backgroundColor: '#D1FAE5',
      color: '#1D9E75',
    },
    verified: {
      backgroundColor: '#D1FAE5',
      color: '#1D9E75',
    },
    approved: {
      backgroundColor: '#D1FAE5',
      color: '#1D9E75',
    },
    pending: {
      backgroundColor: '#FEF3C7',
      color: '#D97706',
    },
    past: {
      backgroundColor: '#E6F1FB',
      color: '#185FA5',
    },
    info: {
      backgroundColor: '#E6F1FB',
      color: '#185FA5',
    },
    suspended: {
      backgroundColor: '#FEE2E2',
      color: '#EF4444',
    },
    rejected: {
      backgroundColor: '#FEE2E2',
      color: '#EF4444',
    },
  },
} as const;

export type Theme = typeof theme;
