/**
 * EdumentX AI — SQL Filter Builder
 *
 * Builds parameterized SQL WHERE clauses from structured search constraints.
 *
 * CRITICAL RULE: SQL is NEVER generated by the LLM. It's built from
 * predefined templates. This prevents SQL injection and ensures
 * type safety.
 *
 * The builder supports:
 *   - Subject matching (array containment)
 *   - Budget range (max and/or min)
 *   - Location (city name match in Phase 1, geospatial in Phase 2)
 *   - Gender preference
 *   - Tutoring mode
 *   - Grade level
 *   - Minimum rating
 *   - Minimum experience
 *   - Verified-only filter (always on by default)
 */

import type { SearchConstraints } from "@/ai/types/constraints.types";
import type { BuiltQuery } from "@/ai/types/search.types";

// ─── Main Builder ────────────────────────────────────────────────────────────

/**
 * Build a SQL WHERE clause and parameter list from search constraints.
 *
 * @param constraints - Structured search constraints
 * @param includeVectorSearch - Whether to include the vector similarity column
 * @returns Object with SQL string and parameter array
 */
export function buildWhereClause(
  constraints: SearchConstraints,
  includeVectorSearch = true,
): BuiltQuery {
  const conditions: string[] = [];
  const params: unknown[] = [];
  let paramIndex = 0;

  // ── Always filter: verified tutors only ──
  conditions.push(`t.verification_status = 'approved'`);
  conditions.push(`t.has_pending_update = false`);

  // ── Subject matching ──
  if (constraints.subject) {
    paramIndex++;
    conditions.push(`t.subjects @> ARRAY[$${paramIndex}]`);
    params.push(constraints.subject);
  }

  // ── Budget: max budget ──
  if (constraints.budget_max !== undefined && constraints.budget_max > 0) {
    paramIndex++;
    conditions.push(`t.monthly_rate_npr <= $${paramIndex}`);
    params.push(constraints.budget_max);
  }

  // ── Budget: min budget ──
  if (constraints.budget_min !== undefined && constraints.budget_min > 0) {
    paramIndex++;
    conditions.push(`t.monthly_rate_npr >= $${paramIndex}`);
    params.push(constraints.budget_min);
  }

  // ── Location (Phase 1: city name ILIKE; Phase 2: ST_DWithin) ──
  if (constraints.location_text) {
    paramIndex++;
    conditions.push(`t.city ILIKE $${paramIndex}`);
    params.push(`%${constraints.location_text}%`);
  }

  // ── Gender preference ──
  // Gender is collected during tutor onboarding (Male / Female / Other)
  // and synced to the Supabase tutors table via the seed script.
  if (constraints.gender_preference) {
    paramIndex++;
    conditions.push(`t.gender = $${paramIndex}`);
    params.push(constraints.gender_preference);
  }

  // ── Tutoring mode ──
  // Note: Add tutoring_mode column to tutors table if needed
  // Currently not filtering by mode — data may not be available

  // ── Grade level ──
  if (constraints.grade_level) {
    paramIndex++;
    conditions.push(`t.grades_teaching @> ARRAY[$${paramIndex}]`);
    params.push(constraints.grade_level);
  }

  // ── Minimum rating ──
  if (constraints.min_rating !== undefined) {
    paramIndex++;
    conditions.push(`t.rating >= $${paramIndex}`);
    params.push(constraints.min_rating);
  }

  // ── Minimum experience ──
  if (constraints.min_experience !== undefined && constraints.min_experience > 0) {
    paramIndex++;
    conditions.push(`t.years_experience >= $${paramIndex}`);
    params.push(constraints.min_experience);
  }

  return {
    sql: conditions.join(" AND "),
    params,
  };
}

/**
 * Build a complete hybrid search query (metadata filters + vector similarity).
 *
 * @param constraints - Structured search constraints
 * @param embeddingParamIndex - The parameter index for the query embedding ($1, $2, etc.)
 * @param limit - Maximum number of results
 * @returns Complete SQL query string
 */
export function buildHybridSearchQuery(
  constraints: SearchConstraints,
  embeddingParamIndex: number,
  limit = 20,
): { sql: string; params: unknown[] } {
  const filter = buildWhereClause(constraints);

  const sql = `
    SELECT
      t.id,
      t.full_name,
      t.username,
      t.headline,
      t.bio,
      t.subjects,
      t.grades_teaching,
      t.years_experience,
      t.monthly_rate_npr,
      t.neighborhood,
      t.city,
      t.latitude,
      t.longitude,
      t.rating,
      t.review_count,
      t.response_rate,
      t.degree,
      t.institution,
      t.photo_url,
      t.demo_video_url,
      te.embedding <=> $${embeddingParamIndex} AS similarity
    FROM tutors t
    INNER JOIN tutor_embeddings te ON te.tutor_id = t.id
    WHERE ${filter.sql}
    ORDER BY te.embedding <=> $${embeddingParamIndex}
    LIMIT ${limit};
  `;

  return { sql, params: filter.params };
}

/**
 * Build a metadata-only search query (no vector similarity).
 * Used when embedding generation fails or as a fallback.
 */
export function buildMetadataOnlyQuery(
  constraints: SearchConstraints,
  limit = 20,
): { sql: string; params: unknown[] } {
  const filter = buildWhereClause(constraints, false);

  const sql = `
    SELECT
      t.id,
      t.full_name,
      t.username,
      t.headline,
      t.bio,
      t.subjects,
      t.grades_teaching,
      t.years_experience,
      t.monthly_rate_npr,
      t.neighborhood,
      t.city,
      t.latitude,
      t.longitude,
      t.rating,
      t.review_count,
      t.response_rate,
      t.degree,
      t.institution,
      t.photo_url,
      t.demo_video_url,
      0 AS similarity
    FROM tutors t
    WHERE ${filter.sql}
    ORDER BY t.rating DESC, t.review_count DESC
    LIMIT ${limit};
  `;

  return { sql, params: filter.params };
}

/**
 * Build a query for related subjects (subject broadening fallback).
 * Uses ILIKE on subjects array to find partial matches.
 */
export function buildRelatedSubjectQuery(
  subject: string,
  limit = 20,
): { sql: string; params: unknown[] } {
  const sql = `
    SELECT
      t.id,
      t.full_name,
      t.headline,
      t.bio,
      t.subjects,
      t.monthly_rate_npr,
      t.city,
      t.rating,
      t.years_experience,
      0 AS similarity
    FROM tutors t
    WHERE t.verification_status = 'approved'
      AND t.has_pending_update = false
      AND EXISTS (
        SELECT 1 FROM unnest(t.subjects) AS s
        WHERE s ILIKE $1
      )
    ORDER BY t.rating DESC
    LIMIT ${limit};
  `;

  return { sql, params: [`%${subject}%`] };
}
