/**
 * markerIcons — Shared image refs for the custom map pins.
 *
 * expo-maps Google markers accept a `SharedRef<'image'>` as their
 * `icon`; expo-image's `Image.loadAsync` produces exactly that. The
 * pins (generated by `scripts/generate-markers.mjs`) are loaded
 * once and cached module-wide.
 *
 * State language (unified with `TutorAvatarPin`):
 *
 *   - pin-tutor.png             slate ring + slate person → regular tutor
 *   - pin-verified.png          green ring + shield      → verified tutor
 *   - pin-cluster.png           slate ring + amber dot   → zoom-in cluster
 *   - pin-tutor-selected.png    amber ring + white halo  → selected tutor
 *   - pin-verified-selected.png amber ring + shield + halo → selected verified
 *   - pin-picker.png            solid amber + white dot  → location picker
 *
 * Amber = selection accent; green = verified (verification token);
 * slate = default. The tail tip sits at the image bottom-center,
 * which matches expo-maps' default marker anchor.
 */
import { Image, type ImageRef } from "expo-image";

export type MarkerIconSet = {
  tutor: ImageRef | null;
  verified: ImageRef | null;
  cluster: ImageRef | null;
  tutorSelected: ImageRef | null;
  verifiedSelected: ImageRef | null;
  picker: ImageRef | null;
};

const PIN_ASSETS = {
  tutor: require("../../../assets/markers/pin-tutor.png"),
  verified: require("../../../assets/markers/pin-verified.png"),
  cluster: require("../../../assets/markers/pin-cluster.png"),
  tutorSelected: require("../../../assets/markers/pin-tutor-selected.png"),
  verifiedSelected: require("../../../assets/markers/pin-verified-selected.png"),
  picker: require("../../../assets/markers/pin-picker.png"),
} as const;

let cache: MarkerIconSet | null = null;
let inflight: Promise<MarkerIconSet> | null = null;

/** Returns the pin refs. Subsequent calls return the cached set. */
export function loadMarkerIcons(): Promise<MarkerIconSet> {
  if (cache) return Promise.resolve(cache);
  if (!inflight) {
    inflight = Promise.all([
      Image.loadAsync(PIN_ASSETS.tutor),
      Image.loadAsync(PIN_ASSETS.verified),
      Image.loadAsync(PIN_ASSETS.cluster),
      Image.loadAsync(PIN_ASSETS.tutorSelected),
      Image.loadAsync(PIN_ASSETS.verifiedSelected),
      Image.loadAsync(PIN_ASSETS.picker),
    ])
      .then(([tutor, verified, cluster, tutorSelected, verifiedSelected, picker]) => {
        cache = { tutor, verified, cluster, tutorSelected, verifiedSelected, picker };
        return cache;
      })
      .finally(() => {
        inflight = null;
      });
  }
  return inflight;
}
