/**
 * markerIcons — Shared image refs for the custom map pins.
 *
 * expo-maps Google markers accept a `SharedRef<'image'>` as their
 * `icon`; expo-image's `Image.loadAsync` produces exactly that. The
 * pins (generated by `scripts/generate-markers.mjs`) are loaded
 * once and cached module-wide:
 *
 *   - pin-tutor.png             amber badge + slate dot  → regular tutor
 *   - pin-verified.png          green badge + white dot  → verified tutor
 *   - pin-cluster.png           slate badge + amber dot  → zoom-in cluster
 *   - pin-tutor-selected.png    amber badge + wide white ring → selected
 *   - pin-verified-selected.png green badge + wide white ring → selected
 *
 * The tail tip sits at the image bottom-center, which matches expo-maps'
 * default marker anchor.
 */
import { Image, type ImageRef } from "expo-image";

export type MarkerIconSet = {
  tutor: ImageRef | null;
  verified: ImageRef | null;
  cluster: ImageRef | null;
  tutorSelected: ImageRef | null;
  verifiedSelected: ImageRef | null;
};

const PIN_ASSETS = {
  tutor: require("../../../assets/markers/pin-tutor.png"),
  verified: require("../../../assets/markers/pin-verified.png"),
  cluster: require("../../../assets/markers/pin-cluster.png"),
  tutorSelected: require("../../../assets/markers/pin-tutor-selected.png"),
  verifiedSelected: require("../../../assets/markers/pin-verified-selected.png"),
} as const;

let cache: MarkerIconSet | null = null;
let inflight: Promise<MarkerIconSet> | null = null;

/** Returns the pin refs. Subsequent calls return the cached set. */
export function loadMarkerIcons(): Promise<MarkerIconSet> {
  if (cache) return Promise.resolve(cache);
  if (!inflight) {
    inflight = Promise.all([
      Image.loadAsync(PIN_ASSETS.tutor),
      Image.loadAsync(PIN_ASSETS.verified),
      Image.loadAsync(PIN_ASSETS.cluster),
      Image.loadAsync(PIN_ASSETS.tutorSelected),
      Image.loadAsync(PIN_ASSETS.verifiedSelected),
    ])
      .then(([tutor, verified, cluster, tutorSelected, verifiedSelected]) => {
        cache = { tutor, verified, cluster, tutorSelected, verifiedSelected };
        return cache;
      })
      .finally(() => {
        inflight = null;
      });
  }
  return inflight;
}