/**
 * ClerkFirebaseBridge — "Silent Bridge" between Clerk (identity) and
 * Firebase (data).
 *
 * Clerk is the source of truth for "is this user authenticated?" and
 * owns the user identity (sign-in, sign-up, sessions, JWTs). Firebase
 * Firestore is the source of truth for app data (user profiles, tutor
 * listings, etc.). They live in separate identity spaces — Clerk mints
 * JWTs for its own session, Firestore has its own custom-token-based
 * auth.
 *
 * The bridge watches Clerk's auth state and, whenever the user is
 * signed in, asks Clerk for a Firebase-shaped custom token (via the
 * `integration_firebase` JWT template configured in the Clerk
 * Dashboard) and silently signs the Firebase Auth client in with it.
 * On sign-out, it does the reverse: signs Firebase out.
 *
 * This is the pattern documented in
 * `Documentation/04-Firebase/Clerk_Integration.md` and the source of
 * the v1 "users/{uid}" key — the Clerk user ID, surfaced through the
 * custom token's `uid` claim, becomes the Firestore document ID. Every
 * Firestore read/write in the app uses this uid, so the bridge and the
 * Firestore security rules agree.
 *
 * Usage in `app/_layout.tsx`:
 *   <ClerkProvider>
 *     <ClerkFirebaseBridge />
 *     <RootLayoutNav />
 *   </ClerkProvider>
 */
import { useEffect, useRef } from "react";
import { useAuth } from "@clerk/clerk-expo";
import { getApp } from "@react-native-firebase/app";
import {
  getAuth,
  signInWithCustomToken,
  signOut as firebaseSignOut,
} from "@react-native-firebase/auth";

/**
 * The name of the JWT template configured in the Clerk Dashboard →
 * Integrations → Firebase. Clerk creates this template automatically
 * when the Firebase integration is enabled. The template mints a token
 * whose payload matches the Firebase custom-token format (the `uid`
 * claim is the Clerk user ID, the rest is a Firebase-shaped base64
 * blob generated by Clerk's integration).
 */
const FIREBASE_JWT_TEMPLATE = "integration_firebase";

export function ClerkFirebaseBridge() {
  const { isLoaded, isSignedIn, getToken, userId } = useAuth();

  // Track the last Clerk user ID we successfully bridged. We re-bridge
  // when the uid changes (sign-in or user switch) but NOT on every
  // `isLoaded` flip. Without this, we'd refetch the JWT on every
  // re-render, which is wasteful and races with the previous
  // `signInWithCustomToken` call.
  const lastBridgedUidRef = useRef<string | null>(null);

  useEffect(() => {
    // Wait for Clerk to finish loading. `isLoaded === false` means
    // Clerk is still resolving the session from the native SecureStore
    // — calling `getToken` now would throw.
    if (!isLoaded) return;

    if (!isSignedIn || !userId) {
      // Signed out — clear the Firebase session so the Firestore
      // security rules no longer grant access. The sign-out is
      // best-effort: if the bridge is just observing a Clerk sign-out
      // that *we* triggered, Firebase is already signed out; the
      // `signOut()` call is a no-op in that case.
      if (lastBridgedUidRef.current !== null) {
        lastBridgedUidRef.current = null;
        const auth = getAuth(getApp());
        firebaseSignOut(auth).catch((err) => {
          // Swallow — the only way this can fail is if the user is
          // already signed out of Firebase. We log to the console for
          // dev-time visibility, but we do NOT crash the app.
          console.warn("ClerkFirebaseBridge: firebaseSignOut failed", err);
        });
      }
      return;
    }

    // Already bridged this user. No-op.
    if (lastBridgedUidRef.current === userId) return;

    // Sign into Firebase with the custom token Clerk mints for us.
    let cancelled = false;
    (async () => {
      try {
        const token = await getToken({ template: FIREBASE_JWT_TEMPLATE });
        if (cancelled) return;
        if (!token) {
          // The integration isn't enabled or the template name is
          // wrong. Surface a clear error — without this token the
          // Firestore writes will fail with `auth/custom-token-mismatch`
          // or `auth/invalid-custom-token`.
          console.error(
            "ClerkFirebaseBridge: getToken returned null. " +
              "Verify the Firebase integration is enabled in the Clerk " +
              "Dashboard and the JWT template is named " +
              `"${FIREBASE_JWT_TEMPLATE}".`,
          );
          return;
        }
        const auth = getAuth(getApp());
        await signInWithCustomToken(auth, token);
        if (cancelled) return;
        lastBridgedUidRef.current = userId;
      } catch (err) {
        console.error("ClerkFirebaseBridge: signInWithCustomToken failed", err);
      }
    })();

    return () => {
      cancelled = true;
    };
  }, [isLoaded, isSignedIn, userId, getToken]);

  // This component is invisible — the only thing it does is manage
  // the Firebase session in the background.
  return null;
}
